### ISSUE TITLE
configure with metasploit 

### ISSUE THREAD

**Issue by pretech86** [scriptjunkie/msfgui#2]
thanks for the tool but how can i configure it with netasploit because it can't execute any command

**Comment by scriptjunkie** [comment]
What OS are you on and how did you install Metasploit?
Assuming you're on Linux, you'd usually, in one terminal, run 
`msfrpcd -U msf -P pass -a 127.0.0.1`
then wait a minute until it's all loaded then you'd start up msfgui and fill in "msf" for the username, "pass" for the password, and "127.0.0.1" for the IP and click connect. Please post if you see any errors from either of those and what exactly the errors say.

**Comment by pretech86** [comment]
![Screenshot from 2019-05-30 02-21-15](https://user-images.githubusercontent.com/46816468/58612784-703cb500-82bc-11e9-8c78-02dadf5256e5.png)
![Screenshot from 2019-05-30 02-22-04](https://user-images.githubusercontent.com/46816468/58612785-70d54b80-82bc-11e9-90d0-b1b6bbe729b8.png)

i use kali linux last version 
when i write the command i got this error .. after that i run msfgui and enter user name and password and it not loaded 

/opt/metasploit/apps/pro/engine/tmp/servicekey.txt

Traceback (most recent call last):
	12: from /usr/bin/msfrpcd:237:in `<main>'
	11: from /usr/bin/msfrpcd:105:in `start_rpc_service'
	10: from /usr/share/metasploit-framework/plugins/msgrpc.rb:94:in `run'
	 9: from /usr/share/metasploit-framework/lib/msf/core/rpc/v10/service.rb:61:in `start'
	 8: from /usr/share/metasploit-framework/lib/rex/service_manager.rb:25:in `start'
	 7: from /usr/share/metasploit-framework/lib/rex/service_manager.rb:81:in `start'
	 6: from /usr/share/metasploit-framework/lib/rex/proto/http/server.rb:145:in `start'
	 5: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.17/lib/rex/socket/tcp_server.rb:29:in `create'
	 4: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.17/lib/rex/socket/tcp_server.rb:39:in `create_param'
	 3: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.17/lib/rex/socket.rb:49:in `create_param'
	 2: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.17/lib/rex/socket/comm/local.rb:33:in `create'
	 1: from /usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.17/lib/rex/socket/comm/local.rb:174:in `create_by_type'
/usr/share/metasploit-framework/vendor/bundle/ruby/2.5.0/gems/rex-socket-0.1.17/lib/rex/socket/comm/local.rb:187:in `rescue in create_by_type': The address is already in use or unavailable: (127.0.0.1:55553). (Rex::BindFailed)

**Comment by scriptjunkie** [comment]
That usually means there is already an msfrpcd running. Try rebooting, starting msfrpcd manually with `msfrpcd -U msf -P pass -a 127.0.0.1` waiting for it to start, then opening msfgui and connecting to the existing one

**Comment by pretech86** [comment]
It working now , but some times not working 
Thanks a lot
