### ISSUE TITLE
How can i compile it without error？

### ISSUE THREAD

**Issue by phpnginx** [scriptjunkie/msfgui#3]
I want to translate this program into my local language，But I don't know java at all，How can i compile it without error？
![image](https://user-images.githubusercontent.com/61927455/104134575-6b5f4300-53c5-11eb-8ad9-019623b5e557.png)
错误 means error

**Comment by scriptjunkie** [comment]
I used the Netbeans IDE to compile. Have you tried that?

**Comment by phpnginx** [comment]
> I used the Netbeans IDE to compile. Have you tried that?

Thank you for reply，I will try it

**Comment by phpnginx** [comment]
It works！！！
